# Generated by RecipeLang compiler

ingredients = {
    "flour": {"amount": 200.0, "unit": "g"},
    "sugar": {"amount": 150.0, "unit": "g"},
    "eggs": {"amount": 3.0, "unit": ""},
    "butter": {"amount": 100.0, "unit": "g"},
    "milk": {"amount": 250.0, "unit": "ml"},
    "cocoa": {"amount": 50.0, "unit": "g"},
}

recipe_name = "Chocolate Cake"
serves      = 8.0
allergens   = ['eggs', 'gluten', 'milk']
diets       = ['vegetarian']

# Scale from 8 to 16 servings (factor 2.0000)
scale_factor = 2.0000
serves = 16.0
for ing in ingredients.values():
    ing["amount"] = round(ing["amount"] * scale_factor, 4)

UNIT_UPGRADE = {
    "g":   (1000, "kg",   0.001),
    "ml":  (1000, "l",    0.001),
    "tsp": (3,    "tbsp", 1/3),
}
for ing in ingredients.values():
    u = ing["unit"]
    if u in UNIT_UPGRADE:
        threshold, bigger, factor = UNIT_UPGRADE[u]
        if ing["amount"] >= threshold:
            ing["amount"] = round(ing["amount"] * factor, 4)
            ing["unit"]   = bigger

# CONVERT milk TO l
CONV = {"g":1,"kg":1000,"ml":1,"l":1000,"tsp":1,"tbsp":3}
_ing = ingredients["milk"]
_base = _ing["amount"] * CONV[_ing["unit"]]
_ing["amount"] = round(_base / CONV["l"], 4)
_ing["unit"]   = "l"

print(f"\n╔══ {recipe_name} ══")
print(f"║   Serves  : {int(serves)}")

if allergens:
    print(f"║   Contains : {", ".join(allergens)}")
else:
    print("║   Allergens: none detected")

DIET_BADGE = {
    "vegan":       "[VEGAN]",
    "vegetarian":  "[VEGETARIAN]",
    "gluten-free": "[GLUTEN-FREE]",
    "dairy-free":  "[DAIRY-FREE]",
    "nut-free":    "[NUT-FREE]",
    "halal":       "[HALAL]",
    "kosher":      "[KOSHER]",
}
if diets:
    badges = " ".join(DIET_BADGE.get(d, f"[{d.upper()}]") for d in diets)
    print(f"║   Diet     : {badges}")
print("╚" + "═" * 40)

print("\nIngredients:")
for name, ing in ingredients.items():
    amt = ing["amount"]
    display = int(amt) if amt == int(amt) else amt
    print(f'  {display}{ing["unit"]}  {name}')

print("\n── PREP ──")
print("  1. Measure and sift all dry ingredients")
print("  Mix: flour, sugar, cocoa")
print("\n── COOK ──")
print("  1. Melt butter in a saucepan")
print("  Mix: butter, eggs, milk")
print("  Bake at 180.0C for 35.0min")
print("\n── ASSEMBLE ──")
print("  1. Remove cake from oven and let cool")
print("  2. Layer cake and apply frosting")
print("\n── SERVE ──")
print("  1. Slice and plate the cake")
print("  2. Dust with powdered sugar")
print("")